"""split_tenant_profile_street_fields

Revision ID: 9ea8f08a9e1f
Revises: d1e2f3a4b5c6
Create Date: 2026-03-15 10:50:20.064767

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ea8f08a9e1f"
down_revision: Union[str, None] = "d1e2f3a4b5c6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenant_profiles", sa.Column("address_street_name", sa.String(length=255), nullable=False)
    )
    op.add_column(
        "tenant_profiles", sa.Column("address_street_number", sa.String(length=20), nullable=False)
    )
    op.drop_column("tenant_profiles", "address_street")
    op.drop_constraint("uq_tenants_public_id", "tenants", type_="unique")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("uq_tenants_public_id", "tenants", ["public_id"])
    op.add_column(
        "tenant_profiles",
        sa.Column("address_street", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("tenant_profiles", "address_street_number")
    op.drop_column("tenant_profiles", "address_street_name")
    # ### end Alembic commands ###
