"""add_transactions_table

Revision ID: c119274a702d
Revises: 932c4186f8ba
Create Date: 2026-02-22 22:32:17.382290

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "c119274a702d"
down_revision: Union[str, None] = "932c4186f8ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("session_id", sa.UUID(), nullable=False),
        sa.Column("tenant_id", sa.UUID(), nullable=False),
        sa.Column("merchant_id", sa.Integer(), nullable=False),
        sa.Column("pos_id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("country", sa.String(length=2), nullable=False),
        sa.Column("language", sa.String(length=2), nullable=False),
        sa.Column("url_return", sa.String(length=512), nullable=False),
        sa.Column("url_status", sa.String(length=512), nullable=False),
        sa.Column("sign", sa.String(length=96), nullable=False),
        sa.Column("wait_for_result", sa.Boolean(), nullable=False),
        sa.Column("regulation_accept", sa.Boolean(), nullable=False),
        sa.Column("status", sa.SmallInteger(), nullable=False),
        sa.Column("p24_order_id", sa.Integer(), nullable=True),
        sa.Column("order", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("note", sa.String(length=1024), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("amount > 0", name="check_transaction_amount_positive"),
        sa.CheckConstraint("status >= 0 AND status <= 3", name="check_transaction_status_range"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("session_id"),
    )
    op.create_index("idx_transactions_status", "transactions", ["status"], unique=False)
    op.create_index("idx_transactions_tenant_id", "transactions", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_transactions_tenant_id", table_name="transactions")
    op.drop_index("idx_transactions_status", table_name="transactions")
    op.drop_table("transactions")
    # ### end Alembic commands ###
