"""remove_user_tenants_table

Revision ID: 40e549d0648d
Revises: eed96e2247c3
Create Date: 2026-02-19 00:59:41.143545

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "40e549d0648d"
down_revision: Union[str, None] = "eed96e2247c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_tenants")
    op.drop_index("ix_tenant_roles_tenant_id", table_name="tenant_roles")
    op.drop_index("ix_tenants_owner_id", table_name="tenants")
    op.drop_index("ix_users_tenant_id", table_name="users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("ix_users_tenant_id", "users", ["tenant_id"], unique=False)
    op.create_index("ix_tenants_owner_id", "tenants", ["owner_id"], unique=False)
    op.create_index("ix_tenant_roles_tenant_id", "tenant_roles", ["tenant_id"], unique=False)
    op.create_table(
        "user_tenants",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("tenant_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["tenant_id"], ["tenants.id"], name="user_tenants_tenant_id_fkey", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="user_tenants_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "tenant_id", name="user_tenants_pkey"),
    )
    # ### end Alembic commands ###
