from core.constants.collections import (
    CANVAS_VERSIONS_COLLECTION,
    KITCHEN_CONFIG_COLLECTION,
    KITCHEN_ORDERS_COLLECTION,
    MENUS_COLLECTION,
    ORDERS_COLLECTION,
)

__all__ = [
    "CANVAS_VERSIONS_COLLECTION",
    "KITCHEN_CONFIG_COLLECTION",
    "KITCHEN_ORDERS_COLLECTION",
    "MENUS_COLLECTION",
    "ORDERS_COLLECTION",
]
