import type { ProfileFormData, TenantProfile } from "@restorio/types";

export const EMPTY_FORM: ProfileFormData = {
  nip: "",
  companyName: "",
  contactEmail: "",
  phone: "",
  addressStreetName: "",
  addressStreetNumber: "",
  addressCity: "",
  addressPostalCode: "",
  addressCountry: "Polska",
  ownerFirstName: "",
  ownerLastName: "",
  ownerEmail: "",
  ownerPhone: "",
  contactPersonFirstName: "",
  contactPersonLastName: "",
  contactPersonEmail: "",
  contactPersonPhone: "",
  socialFacebook: "",
  socialInstagram: "",
  socialTiktok: "",
  socialWebsite: "",
};

export const toFormData = (profile: TenantProfile): ProfileFormData => ({
  nip: profile.nip,
  companyName: profile.companyName,
  contactEmail: profile.contactEmail,
  phone: profile.phone,
  addressStreetName: profile.addressStreetName,
  addressStreetNumber: profile.addressStreetNumber,
  addressCity: profile.addressCity,
  addressPostalCode: profile.addressPostalCode,
  addressCountry: profile.addressCountry,
  ownerFirstName: profile.ownerFirstName,
  ownerLastName: profile.ownerLastName,
  ownerEmail: profile.ownerEmail ?? "",
  ownerPhone: profile.ownerPhone ?? "",
  contactPersonFirstName: profile.contactPersonFirstName ?? "",
  contactPersonLastName: profile.contactPersonLastName ?? "",
  contactPersonEmail: profile.contactPersonEmail ?? "",
  contactPersonPhone: profile.contactPersonPhone ?? "",
  socialFacebook: profile.socialFacebook ?? "",
  socialInstagram: profile.socialInstagram ?? "",
  socialTiktok: profile.socialTiktok ?? "",
  socialWebsite: profile.socialWebsite ?? "",
});
